export const avatarOptions = {
  skinColor: [
    "Tanned",
    // "Yellow",
    "Pale",
    "Light",
    "Brown",
    "DarkBrown",
    "Black",
  ],

  topType: [
    // "NoHair",
    // "Eyepatch",
    "Hat",
    "Hijab",
    "Turban",
    // "WinterHat1",
    // "WinterHat2",
    // "WinterHat3",
    // "WinterHat4",
    // "LongHairBigHair",
    "LongHairBob",
    "LongHairBun",
    "LongHairCurly",
    // "LongHairCurvy",
    // "LongHairDreads",
    "LongHairFrida",
    // "LongHairFro",
    "LongHairFroBand",
    "LongHairNotTooLong",
    // "LongHairShavedSides",
    "LongHairMiaWallace",
    // "LongHairStraight",
    // "LongHairStraight2",
    "LongHairStraightStrand",
    "ShortHairDreads01",
    "ShortHairDreads02",
    "ShortHairFrizzle",
    "ShortHairShaggyMullet",
    "ShortHairShortCurly",
    "ShortHairShortFlat",
    "ShortHairShortRound",
    "ShortHairShortWaved",
    // "ShortHairSides",
    "ShortHairTheCaesar",
    "ShortHairTheCaesarSidePart",
  ],
  hairColor: [
    "Brown",
    "Black",
    "Blonde",
    // "BlondeGolden",
    "Auburn",
    // "BrownDark",
    // "PastelPink",
    "Blue",
    // "Platinum",
    "Red",
    // "SilverGray",
  ],
  mouthType: [
    "Concerned",
    "Default",
    "Disbelief",
    "Eating",
    "Grimace",
    "Sad",
    "ScreamOpen",
    "Serious",
    "Smile",
    "Tongue",
    "Twinkle",
    "Vomit",
  ],

  eyebrowType: [
    "Angry",
    "AngryNatural",
    "Default",
    "DefaultNatural",
    "FlatNatural",
    "RaisedExcited",
    "RaisedExcitedNatural",
    "SadConcerned",
    "SadConcernedNatural",
    "UnibrowNatural",
    "UpDown",
    "UpDownNatural",
  ],
  //   graphicType: [
  //     "Bat",
  //     "Cumbia",
  //     "Deer",
  //     "Diamond",
  //     "Hola",
  //     "Pizza",
  //     "Resist",
  //     "Selena",
  //     "Bear",
  //     "SkullOutline",
  //     "Skull",
  //   ],

  eyeType: [
    "Close",
    "Cry",
    "Default",
    "Dizzy",
    "EyeRoll",
    "Happy",
    "Hearts",
    "Side",
    "Squint",
    "Surprised",
    "Wink",
    "WinkWacky",
  ],
  clotheColor: [
    "Black",
    // "Blue01",
    "Blue02",
    "Blue03",
    // "Gray01",
    "Gray02",
    "Heather",
    "PastelBlue",
    "PastelGreen",
    "PastelOrange",
    "PastelRed",
    "PastelYellow",
    "Pink",
    "Red",
    // "White",
  ],
  clotheType: [
    // "BlazerShirt",
    "CollarSweater",
    // "GraphicShirt",
    "Hoodie",
    "Overall",
    "ShirtCrewNeck",
    "ShirtScoopNeck",
    "ShirtVNeck",
    // "BlazerSweater",
  ],
  facialHairColor: [
    "Auburn",
    "Black",
    "Blonde",
    "BlondeGolden",
    "Brown",
    "BrownDark",
    "Platinum",
    "Red",
  ],
  facialHairType: [
    "Blank",
    "BeardMedium",
    "BeardLight",
    "BeardMajestic",
    "MoustacheFancy",
    "MoustacheMagnum",
  ],

  accessoriesType: [
    "Blank",
    "Kurt",
    // "Prescription01",
    "Prescription02",
    "Round",
    "Sunglasses",
    "Wayfarers",
  ],

};

{
  /* <Avatar
  avatarStyle='Circle'
  topType='LongHairCurly'
  accessoriesType='Prescription01'
  hairColor='Blue'
  facialHairType='MoustacheFancy'
  facialHairColor='BlondeGolden'
  clotheType='GraphicShirt'
  clotheColor='Pink'
  graphicType='Diamond'
  eyeType='Side'
  eyebrowType='SadConcernedNatural'
  mouthType='Smile'
  skinColor='Brown'
/> */
}
